services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "./bin/dev"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
